name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build package
      - run: npm run build
      - name: cd to dist folder
      - run: cd dist/freshdesk-widget
      - name: creating .npmrc file
      - run: touch .npmrc
      - name: write .npmrc
      - run: |
          echo "@estafsar:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${{ secrets.READ_GITHUB_PACKAGES_TOKEN }}" >> .npmrc
          cat .npmrc
          pwd
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      # - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
      - name: install deps
      - run: npm ci
      - name: build package
      - run: npm run build
      - name: cd to dist folder
      - run: cd dist/freshdesk-widget
      - name: creating .npmrc file
      - run: touch .npmrc
      - name: write .npmrc
      - run: |
          echo "@estafsar:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${{ secrets.READ_GITHUB_PACKAGES_TOKEN }}" >> .npmrc
          cat .npmrc
          pwd
      - name: publish the package
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
