name: Node.js Package

on:
  push:
    branches:
      - master

jobs:

  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.3
          registry-url: https://npm.pkg.github.com/
      - name: install deps
        run: npm ci
      - name: build package
        run: |
          npm run build
          cd dist
          touch .npmrc
          echo "@estafsar:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${{ secrets.READ_GITHUB_PACKAGES_TOKEN }}" >> .npmrc
          cat .npmrc
          pwd
          ls -aR
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
